import json
import shutil
import time
import subprocess
import urllib.parse
import urllib.request
import pyautogui
from tkinter.messagebox import askyesno
import ollama 
import spinner 
import settings
import overwrites
from text_tools import cleanup
from playwright.sync_api import sync_playwright

def get_tools():
    if settings.GOOGLE_KEY!="":
        return [CONSOLE_TOOL,WIKI_TOOL,WEB_TOOL,TEXT_TOOL]
    return [CONSOLE_TOOL,WIKI_TOOL,TEXT_TOOL]

def get_function_by_name(fn_name):
    if(fn_name=="run_console_command"):
        return run_console_command
    elif(fn_name=="fetch_wikipedia_content"):
        return fetch_wikipedia_content
    elif(fn_name=="fetch_website"):
        return fetch_website
    elif(fn_name=="type_text"):
        return type_text

CONSOLE_TOOL = {
    "type": "function",
    "function": {
        "name": "run_console_command",
        "description": (
            "Run a bash command generated by you in the linux console. "
            "Always use this if the user is asking for an action, that you normally cannot perform. "
            "Also use this command if the user asks for Information, that can be obtained with a system command. "
            "You can for example use this tool to get the date, list, create and write files, and everything else that can be done with a bash command. "
            "Never use this to access information from the internet or wikipedia. "
            "If the result is an error, correct the command and try again. "
            "You do not need to be carefull when running a system command. "
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "command": {
                    "type": "string",
                    "description": "The bash command, you want to execute",
                },
            },
            "required": ["command"],
        },
    },
}

WIKI_TOOL = {
    "type": "function",
    "function": {
        "name": "fetch_wikipedia_content",
        "description": (
            "Search Wikipedia and fetch the introduction of the most relevant article. "
            "Always use this if the user is asking for information that is likely on wikipedia. "
            "If the user has a typo in their search query, correct it before searching. "
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "search_query": {
                    "type": "string",
                    "description": "Search query for finding the Wikipedia article",
                },
            },
            "required": ["search_query"],
        },
    },
}

WEB_TOOL = {
    "type": "function",
    "function": {
        "name": "fetch_website",
        "description": (
            "Returns the a summary of the text content of the first website for a given search query. "
            "Always use this if the user is asking for information that is likely on websites other than wikipedia. "
            "If the user has a typo in their search query, correct it before searching."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": "The search query to get information about",
                },
            },
            "required": ["query"],
        },
    },
}

TEXT_TOOL = {
    "type": "function",
    "function": {
        "name": "type_text",
        "description": (
            "Controls the users keyboard to type a provided text into a text field. "
            "Use this functin, if the user asks you to type down or write down a text. "
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "text": {
                    "type": "string",
                    "description": "The text to type",
                },
            },
            "required": ["text"],
        },
    },
}

def run_console_command(command: str) -> dict:
    command=command.replace('\\n', '\n').replace('\\t', '\t').replace('\\','')
    terminal_width = shutil.get_terminal_size().columns
    print("\n" + "=" * terminal_width+"\n")
    time.sleep(1)
    e=-2
    while(e==-2):
        messages_eval = [
            {
                "role": "system",
                "content": (
                    "You are an assistant that interprets linux console commands. "
                    "When prompted with a command, state accurately and truthfully, what that command does. "
                    "Keep your response brief but include all relevant information. "
                    "/no_think"
                ),
            }
        ]
        messages_eval.append({"role": "user", "content": command})
        with spinner.Spinner("Interpreting..."):
            #text = tokenizer.apply_chat_template(messages_a, tools=tools, add_generation_prompt=True, tokenize=False)
            response = ollama.chat(
                model= settings.LLM_MODEL_E,
                messages= messages_eval,
                keep_alive= 0,
            )
        if askyesno("Confirm command execution", command+"\n\n"+response.message.content.replace("<think>\n","").replace("</think>\n","")):
            e=1
        else:
            e=0       
    if(e==1):
        overwrites.print("Executing command: "+command+"\n")
        p = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
        output, error = p.communicate()
        if p.returncode != 0:
            print("\n"+"-" * terminal_width+"\n")
            print("Error calling command: "+error.decode())
            print("=" * terminal_width + "\n")
            return {
                "command": command, "output": error.decode(), "status": "failed"
            }
        else:
            print("\n"+"-" * terminal_width+"\n")
            if(output.decode()=="" and error.decode()!=""):
                print(error.decode())
            else:
                print(output.decode())
            print("=" * terminal_width + "\n")
            if(output.decode()=="" and error.decode()!=""):
                return {"command": command, "output": error.decode(), "status": "error"}
            else:
                return {"command": command, "output": output.decode(), "status": "success"}
    elif(e==0):
        print("\n"+"-" * terminal_width+"\n")
        print("Command denied by user")
        print("=" * terminal_width + "\n")
        return {
            "command": command, "output": "command denied by user", "status": "denied"
        }

def fetch_wikipedia_content(search_query: str) -> dict:
    """Fetches wikipedia content for a given search_query"""
    overwrites.print("Fetching wikipedia content for "+search_query)
    try:
        # Search for most relevant article
        search_url = "https://en.wikipedia.org/w/api.php"
        search_params = {
            "action": "query",
            "format": "json",
            "list": "search",
            "srsearch": search_query,
            "srlimit": 1,
        }

        url = f"{search_url}?{urllib.parse.urlencode(search_params)}"
        with urllib.request.urlopen(url) as response:
            search_data = json.loads(response.read().decode())

        if not search_data["query"]["search"]:
            return {
                "status": "error",
                "message": f"No Wikipedia article found for '{search_query}'",
            }

        # Get the normalized title from search results
        normalized_title = search_data["query"]["search"][0]["title"]

        # Now fetch the actual content with the normalized title
        content_params = {
            "action": "query",
            "format": "json",
            "titles": normalized_title,
            "prop": "extracts",
            "exintro": "true",
            "explaintext": "true",
            "redirects": 1,
        }

        url = f"{search_url}?{urllib.parse.urlencode(content_params)}"
        with urllib.request.urlopen(url) as response:
            data = json.loads(response.read().decode())

        pages = data["query"]["pages"]
        page_id = list(pages.keys())[0]

        if page_id == "-1":
            return {
                "status": "error",
                "message": f"No Wikipempg123 /usr/share/sounds/ubuntu/stereo/positive-acknowledge.wavdia article found for '{search_query}'",
            }

        content = pages[page_id]["extract"].strip()
        return {
            "status": "success",
            "content": content,
            "title": pages[page_id]["title"],
        }

    except Exception as e:
        return {"status": "error", "message": str(e)}

def fetch_website(query:str) -> dict:
    overwrites.print("Getting page for "+query)

    # Query Google Custom Search API
    search_url = "https://www.googleapis.com/customsearch/v1"

    params = {
        "key": settings.GOOGLE_KEY,
        "cx": settings.GOOGLE_ID,
        "q": query,
    }

    try:
        with urllib.request.urlopen(f"{search_url}?{urllib.parse.urlencode(params)}") as response:
            search_results = json.loads(response.read().decode())
            results = search_results.get("items", [])
    except Exception as e:
        return {"status": "error", "message": str(e)}
    for result in results:
        url = result["link"]
        print(url)
        try:
            with sync_playwright() as p:
                browser = p.chromium.launch(headless=True)  # Set headless=False to see the browser
                context = browser.new_context(java_script_enabled=True)  # Ensure JavaScript is enabled
                page = context.new_page()
                page.goto(url)

                page.wait_for_selector("body")

                head_text = cleanup(page.locator("head").text_content()).splitlines()[0]
                body_text = cleanup(page.locator("body").text_content())
                
                browser.close()

            lines = body_text.splitlines()
            body_summary = ""
            lines_per_chunk = 40
            for i in range(0, len(lines), lines_per_chunk):
                messages_eval = [
                    {
                        "role": "system",
                        "content": (
                            "You are an assistant that interprets text from a website. "
                            "The next user message is the text that is vissible on a webpage. "
                            f"Summarize all information, that is relevant to this search-query: {query} "
                            "Remove control elements, cookie forms, marketing and more. "
                            "Do not state, what the website does, just extract the actual information written on the website. "
                            "If no relevant information is in the text, say nothing. "
                            "Keep your answer very short and conzise. "
                            "/no_think"
                        ),
                    }
                ]
                messages_eval.append({"role": "user", "content": "\n".join(lines[i:i + lines_per_chunk])})
                with spinner.Spinner(f"Interpreting {i}/{len(lines)} ..."):
                    #text = tokenizer.apply_chat_template(messages_a, tools=tools, add_generation_prompt=True, tokenize=False)
                    response = ollama.chat(
                        model= settings.LLM_MODEL,
                        messages= messages_eval,
                        keep_alive= 10,
                    )
                body_summary += response.message.content.replace("<think>\n","").replace("</think>\n","")

            lastlen = len(lines)
            dlen = lastlen
            
            while dlen!=0:
                lines = body_summary.splitlines()
                dlen = lastlen - len(lines)
                lastlen = len(lines)
                body_summary = ""
                lines_per_chunk = 40
                for i in range(0, len(lines), lines_per_chunk):
                    messages_eval = [
                        {
                            "role": "system",
                            "content": (
                                "You are an assistant that interprets text from a website. "
                                "The next user message is the text that is vissible on a webpage. "
                                "Keep your answer short and conzise. "
                                f"Summarize all information, that is relevant to this search-query: {query} "
                                "/no_think"
                            ),
                        }
                    ]
                    messages_eval.append({"role": "user", "content": "\n".join(lines[i:i + lines_per_chunk])})
                    with spinner.Spinner(f"Interpreting {i}/{len(lines)} ..."):
                        #text = tokenizer.apply_chat_template(messages_a, tools=tools, add_generation_prompt=True, tokenize=False)
                        response = ollama.chat(
                            model= settings.LLM_MODEL,
                            messages= messages_eval,
                            keep_alive= 10,
                        )
                    body_summary += response.message.content.replace("<think>\n","").replace("</think>\n","")

            with open("source.html", "w") as f:
                f.write(head_text)
                f.write(body_summary)

            resp={"status": "success","query": query, "page_url": url, "page_body": body_summary}
            
            return (resp)
        except Exception as e:
            # Close the WebDriver
            print(e)
    return {"status": "error", "message": "no matching webpages were found"}
        
def type_text(text:str) -> dict:

    overwrites.print("Typing: "+text)
    
    pyautogui.typewrite(text)

    resp={"status": "success"}
    return (resp)